import Head from 'next/head'
import Image from 'next/image'
import React from "react";
import styles from '../styles/Home.module.css'
import PortfolioForm from "../src/components/PortfolioForm";
import PortfolioVenn from "../src/components/PortfolioVenn";
import {PortfolioProvider} from "../src/components/PortfolioProvider";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Fund Analysis</title>
                <meta name="description" content="Generated by open software"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Portfolio Analyzer
                </h1>
                <PortfolioProvider>
                    <PortfolioForm />
                    <PortfolioVenn />
                </PortfolioProvider>
            </main>

            <footer className={styles.footer}>
                <a
                    href="hhttps://github.com/HakAl/funds"
                    target="_blank"
                    rel="noopener noreferrer">
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/wave.svg" alt="wave" height={25} width={25}/>
                    </span>
                    {' '}open software
                </a>
            </footer>
        </div>
    )
}
